### ISSUE TITLE
May we get rid of Singletons and static members?

### ISSUE THREAD

**Issue by RodionGork** [DataArt/CalculationEngine#5]
Currently the code relies on `ExternalServices` class which is a singleton (and probably there are more). This means that user wishing to have more than one "context" will have a good coding puzzle.

It would be probably more convenient if we have a context as a normal instance. As some classes/methods need to refer to the context (without passing it to them directly) it, probably, would be good if all the DataModels, Evaluators, FunnyFunctions etc are created using the context as a factory, i.e.

```
IDataModel dm = context.newDataModel(someTable);
SpreadsheetEvaluator se = context.newSpreadsheetEvaluator(dm);
```

In this case the context will be able to assign backrefs to itself for those classes which need them or something like this.

I understand this is not going to be the easy matter so of course it is up to developers to decide whether something like this could be done... :)

**Comment by rroschin** [comment]
Done in 0.7.0.4.dev with GlobalContext:
  `EvaluationContext ec = new EvaluationContext();`
  `ec.put(DataModelAccessor.class, new DataModelAccessor());`
  `new SpreadsheetEvaluator(new DataModel(), ec);`

All custom functions will try to get External access from EvaluationContext first, if not found - from singleton.
